### ISSUE TITLE
Get both staged and unstaged change set when analysing git repository

### ISSUE THREAD

**Issue by antranapp** [mikeger/XcodeSelectiveTesting#19]
First of all, thank you for this great tool.

I was trying to create a git pre-commit hook using this script to run required unit tests before committing but the script always return 0 change set.

After taking a look at the [Git command](mikeger/XcodeSelectiveTesting/Sources/Git/Git+Changeset.swift), it looks like that we need to use `git diff --cached` to get the staged changes.

For better coverage, I think we should get both staged and unstaged changes to analyse what tests should be executed.

**Comment by mikeger** [comment]
Hye @antranapp , based on this approach I've been able to take in account both staged and unstaged files: https://github.com/mikeger/XcodeSelectiveTesting/pull/21

This seems to be a reasonable approach since the actual changeset is taken into account. It is probably not relevant which changes were already staged and which not.

**Comment by antranapp** [comment]
@mikeger I install the branch and tested it. It works as expected. Thank you for the quick implementation 👌

**Comment by antranapp** [comment]
Just a side note, I wrote a blog about your tool https://antran.app/2024/ios_selective_testing/

I'll update the section about this issue as soon as you merge the MR and release a new tag 🙏

**Comment by mikeger** [comment]
It is merged, you can use release 0.9.5: https://github.com/mikeger/XcodeSelectiveTesting/releases/tag/0.9.5
