### ISSUE TITLE
Security Concerns with DependencyGraph

### ISSUE THREAD

**Issue by Pierce-Evan** [mikeger/XcodeSelectiveTesting#3]
The DependencyGraph+DOT class has a couple of built in features which will cause significant security concerns for many companies.

Specifically, there is an option to renderToASCII, which would also send the project architecture information to another private site (dot-to-ascii.ggerganov.com/dot-to-ascii.php) with a URLRequest.

Also, it automatically uploads project architectural information to cdn.jsdeliver.net to use Mermaid for more visualizations.  This seems to use open source versioning, but it does so by running a shell command that opens a browser and sends the architecture info to it through a hard-codes string url. It would be much preferable to use more common dependency definitions, like how you're doing with your other package dependencies (AEXML, etc.).

I'm sure the visuals are good and helpful, but as long as they are private or using unorthodox dependency management, this will be a significant obstacle for many companies to use. Even for basic architecture information, IP is closely guarded.

If these utilities could be added as standard open source project dependencies, instead of private websites, that would allow users to review the code for security concerns and build confidence.  For many companies, that is a requirement before adopting a solution like this.

Alternatively, if the visualizations can't be ported into open source dependencies which don't require sending sensitive architectural info to private servers, perhaps those features could be removed to encourage adoption.

**Comment by mikeger** [comment]
Hey @Pierce-Evan, thanks for bringing this topic up.

I completely agree that security should be on top of mind for any tool that is touching the potentially proprietary source code.

I would like to highlight that rendering the dependency graph is an optional flag that is off per default and is only intended for debugging and initial setup purposes.

Currently, the code in renderInASCII is not used as I also was aware of a potential code structure leak. I will remove this code in question in the coming days to remove any confusion.

Instead, the default implementation is using a Mermaid-based local rendering. 

I must admit the Mermaid solution might be hard to see through. Contrary to your understanding, the Mermaid-based solution that is triggered with the current flag is not uploading the Mermaid graph to any server. Instead, it is creating a webpage that consists of two components: 

- Import of [MermaidJS](https://www.npmjs.com/package/mermaid) via a CDN
- Locally executed JS code that contains embedded Mermaid source

This webpage is packaged into a URL and opened in your browser.

I would also add a detailed description of this function to Wiki to reference it.

Would you see a better solution to include a copy of MermaidJS along this library and embed it into the locally served HTML?

I would most certainly prefer that the bigger companies could adopt my solution since bigger companies can benefit from it the most. Because of that, I would like to encourage you or your colleagues to report any issues concerning security or general ones.

**Comment by mikeger** [comment]
@Pierce-Evan after some troubles with trying to embed Javascript library into the Swift codebase I decided to go with an intermediate solution which would allow using Graphviz output. Please check the corresponding pull request 🙇
